### PR TITLE
Remove Mega-CD support from Eke-Eke

### PR DESCRIPTION
**Pull request by Kekun**
Remove all code from Eke-Eke (hence, the Mega-CD support) to allow moving PicoDrive to a free license.

Admittedly this commit is somewhat dirty as it still exposes Mega-CD support to the user.

I propose the following:
- keep this as a separate branch
- change the license of the code from this branch to some free one
- any commit sent to master must be dual licensed under MAME and the new license and should be pushed on the "free" branch
- add Mega-CD support from MAME
- merge on master
- celebrate the new license :)

### CODE REVIEW

**Comment by mudlord** [comment]
Uh, no?

**Comment by Kekun** [comment]
Why not? Check issue #41.

**Comment by mudlord** [comment]
You are still left with notaz's decision.

**Comment by Kekun** [comment]
Well of course, I am forcing nothing but just proposing a change. :)

In the worst case I would really like to have the code on this branch to move to a free license, which implies the authors to be OK with that (Eke-Eke isn't hence the removal of his code), whether we merge it back once Mega-CD support is added back or not.

**Comment by hooby3dfx** [comment]
What testing have you done on this branch so far?

**Comment by Kekun** [comment]
@hooby3dfx I tested some Mega Drive and 32X games and they were working perfectly, I don't remember how though and it was quite some time ago. I didn't test loading disc games as I expected it to fail miserably as the controls has not been removed from the menus but the backend was removed.

**Comment by notaz** [comment]
Breaking the emulator is not acceptable to me, sorry. See issue #41 for an alternative proposal.

**Pull request closed without merging**
